strictness: medium
test-warnings: false
autodetect: false
member-warnings: false

ignore-patterns:
  - '/migrations/[0-9]{4}_[_a-zA-Z0-9]+.py$'
ignore-paths:
  - src/uptime_report/_version.py
  - versioneer.py
  - build
